### ISSUE TITLE
az bicep hangs if you need an upgrade

### ISSUE THREAD

**Issue by pamelafox** [kjaymiller/cookiecutter-relecloud#100]
I got:

(.venv) ?1cookiecutter-relecloud % az bicep version
A new Bicep release is available: v0.20.4. Upgrade now by running "az bicep upgrade".
Bicep CLI version 0.16.2 (de7fdd2b33)

New Azure CLI version available. Running 'az upgrade' to update automatically.
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): Y

**Comment by kjaymiller** [comment]
I feel this is going to be a hard challenge to replicate without downgrading az cli. I'm going to keep this open.

There are some options like:
- running `az upgrade --all --yes --only-show-erros`. **Probably a bad idea** (https://github.com/Azure/azure-cli/issues/16617)
- doing a version check and raising an error if not up to date. **A likely nightmare to maintain**

I don't get the hanging and I am running `2.49.0`

**Comment by kjaymiller** [comment]
can't repro but please reopen if it happens again
