### ISSUE TITLE
Create GH-Action Tests for new builds

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/cookiecutter-relecloud#101]
Inspo - https://github.com/pamelafox/django-quiz-app/blob/main/.github/workflows/check.yaml

When a new project is generated and pushed to github the test should run.

**Comment by kjaymiller** [comment]
@pamelafox - just to verify this issue is all set?

**Comment by pamelafox** [comment]
I need to test it for FastAPI still.
