### ISSUE TITLE
Makes Note of why environment vars are named as such for postgres-aca-addon

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/cookiecutter-relecloud#103]
The ACA Postgres addon requires specific naming of your environment variables.

We should include this in a comment for that selection.

```python

{% if db_platform == postgres-aca-addon %}
# These variable names are required by the postgres-aca-addon
{% endif %}

**Comment by pamelafox** [comment]
Fixed in https://github.com/kjaymiller/cookiecutter-relecloud/pull/110
I put the comment in the settings file for each framework.
