### ISSUE TITLE
Update README title of generated projects based on the entry path

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/cookiecutter-relecloud#106]
Currently if you select FastAPI, it always reads - 

> Deploy a FastAPI Application via Azure Container Apps

> This project deploy a [FastAPI](https://fastapi.tiangolo.com/) application to [Azure Container Apps](https://aka.ms/aca). The FastAPI application is a simple web application for a space travel agency. The application is built using the FastAPI framework and uses a PostgreSQL database with SQLModel as an ORM. The application can be deployed to Azure using the [Azure Developer CLI](https://learn.microsoft.com/azure/developer/azure-developer-cli/overview).

This could be deterministic based on the choices. 

create a dictionary that is passed in as a jinja extension that is based on the cookiecutter choice and then call those values. This will ensure they are consistent in naming across the templates

**Comment by pamelafox** [comment]
Yeah I think we either remove it / make it super vague, or we add a dict of config keys to nice names, "appservice = "Azure App Service" and dynamically build README descrip from that.

**Comment by kjaymiller** [comment]
I like the large config keys dictionary (reminds me of `abbreviations.json`) perhaps it can be setup similarly and then referenced by an extension so that you just call {% build_ref["{{cookiecutter.db_framework}}" %}

**Comment by kjaymiller** [comment]
added in #127
