### ISSUE TITLE
mongo seed option to drop collection

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/cookiecutter-relecloud#126]
The current logic for the `mongo_seeder.py` is to skip any existing data entries... This was done to prevent errors when running the seeder multiple times.

I suggest doing two things:

1. Add a `--drop` flag to the seeder that will drop the collection before seeding if any data exists.

2. Create a warning that will be displayed if the `--drop` flag is not used and data already exists in the collection. The warning should be something like:

```
WARNING: Data already exists in the collection. If you want to drop the collection and re-seed, use the --drop flag.
```

**Comment by pamelafox** [comment]
sgtm!
