### ISSUE TITLE
Deployment with azd up fails for app container

### ISSUE THREAD

**Issue by chanezon** [kjaymiller/cookiecutter-relecloud#154]
I generated a project with azure_flask_postgres_flexible_aca.
It runs locally in a dev container very nicely.
However deployment of ACA service fails.
I deployed in eastus2

```
 (✓) Done: Container Apps Environment: pat-relecloud-cf65kodvnmfhy-containerapps-env

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ParameterOutOfRange: The value of the 'Version' should be in: []. Verify that the specified parameter value is correct.

TraceID: 2e56c94d2c141b35a444ef129ddc8940
  |       | Creating/Updating resource
```

**Comment by pamelafox** [comment]
MSFT employees cannot create PostgreSQL flex servers in eastus2, please try eastus. I have asked the team many times to produce a better error message but unfortunately have made no progress.

**Comment by pamelafox** [comment]
See also https://github.com/Azure/azure-dev/issues/933

**Comment by chanezon** [comment]
Thank you @pamelafox , I'm trying eastus and closing this bug!

**Comment by chanezon** [comment]
Yes it works fine!

**Comment by kjaymiller** [comment]
Thank you for logging this. We keep running into this issue an never documented it.

I've created #155 so that it can be referenced in the future.
