### ISSUE TITLE
Is pip upgrade needed?

### ISSUE THREAD

**Issue by pamelafox** [kjaymiller/cookiecutter-relecloud#157]
I'm just comparing our repo to other samples, and notice this last line in Dockerfile_dev:

RUN python -m pip install --upgrade pip

Is that necessary? Is it because the python images have outdated pip versions? I'm trying to make sure I understand the reasoning - it's very possible it's necessary.

**Comment by kjaymiller** [comment]
As Prady mentions in https://stackoverflow.com/a/56504368, I've always considered it best practice. This is definitely an "IDK I've always done it moment" but I think it's a common thing.

**Comment by pamelafox** [comment]
Okay, sounds good!
