### ISSUE TITLE
Add restart:unless-stopped to docker-compose-dev.yaml db service

### ISSUE THREAD

**Issue by pamelafox** [kjaymiller/cookiecutter-relecloud#158]
I have that in my other similar dev containers, and I think we want it here as well, unless you think otherwise. The default value for restart is "no".

**Comment by kjaymiller** [comment]
As it's for the devcontainer I don't see a problem with adding it.

Do you know how that handles errors? I ask as I've had containers talk to old volumes and those volumes weren't migrated correctly. Could this cause some stop/start loops?

**Comment by pamelafox** [comment]
This is the reference for it:
https://docs.docker.com/compose/compose-file/compose-file-v3/#restart

I'm really not sure, this is pushing my Docker expertise. Could ask in Cloud Native channel?

**Comment by pamelafox** [comment]
I did end up adding it in that PR, so we could close this, or leave it open until we have your Qs answered.
