### ISSUE TITLE
Add launch.json for each framework for debugging

### ISSUE THREAD

**Issue by pamelafox** [kjaymiller/cookiecutter-relecloud#161]
I've added it for Flask in pr #160 , we should add for Django and FastAPI as well. I have configurations from other projects, just search owner:pamelafox path:launch.json on GitHub. Django is the trickiest due to a setting needed around error propagation.

**Comment by kjaymiller** [comment]
Thinking of the docs writers that often want as simple repos as possible. Do we think that's something we should include.

I love tasks and debug launch settings but wonder if docs writers will not like them.

That being said I agree they should exist but I would be open to removing them if there was push back

**Comment by pamelafox** [comment]
I do think tasks.json is overkill but I really like when debugging just works, especially since debugger is a first class feature of VS Code. And yes, there are built-in launch.json configurations for Flask/FastAPI/Django, but they often require additional tinkering that is really easy to mess up. Most of the time I end up print()ing if I don't already have launch.json setup because I'm too intimidated by the process of configuring it.

So I'm a +1 for launch.json personally. Hopefully Bob's on board.

**Comment by pamelafox** [comment]
Seems to work across Django/FastAPI/Flask
