### ISSUE TITLE
Add `ms-azuretools.vscode-bicep` extension to DevContainer

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/cookiecutter-relecloud#163]
The incorrect version was removed in #160. The correct id is below

----

              The extension id is - `ms-azuretools.vscode-bicep`. Can we add that in?

_Originally posted by @kjaymiller in https://github.com/kjaymiller/cookiecutter-relecloud/pull/160#discussion_r1330786294_

**Comment by pamelafox** [comment]
That's already there! https://github.com/kjaymiller/cookiecutter-relecloud/blob/b8b0b53e7055267b4ba43063e3dcc20ab0034ed0/%7B%7Bcookiecutter.__src_folder_name%7D%7D/.devcontainer/devcontainer.json#L24

Thats why I just rm'ed the redundant non-existent one.
