### ISSUE TITLE
Django local server: Not found: favicon.ico

### ISSUE THREAD

**Issue by pamelafox** [kjaymiller/cookiecutter-relecloud#213]
This isn't really an error, but it does throw new developers off to immediately see an error in their logs about no favicon, so we may want to add a favicon.ico route for all the frameworks.

**Comment by kjaymiller** [comment]
What I'm hearing is that we need a super cool favicon... Perhaps bit on a rocket?

**Comment by pamelafox** [comment]
Lol yes do it.
