### ISSUE TITLE
Provide local run option that works on Window (!gunicorn)

### ISSUE THREAD

**Issue by pamelafox** [kjaymiller/cookiecutter-relecloud#223]
See https://github.com/Azure-Samples/azure-django-postgres-flexible-aca/issues/68

**Comment by kjaymiller** [comment]
Definitely a priority issue that needs to be resolved quickly. We'll have to look into proper testing on windows devices. (I believe there is a way to do this with GH Actions)

**Comment by pamelafox** [comment]
I actually just added windows to the matrix for the openai sample as we had Windows issues this week, so yep, we can do some testing with GitHub actions. For this particular issue, we'd need to add a test to check the local run command, in addition to our live server tests. Seems useful!
