### ISSUE TITLE
Fetch secrets from key vault instead

### ISSUE THREAD

**Issue by pamelafox** [kjaymiller/cookiecutter-relecloud#49]
ACA just added support for getting secrets from key vault!

https://learn.microsoft.com/en-us/azure/container-apps/manage-secrets?tabs=arm-template#reference-secret-from-key-vault

It might be slightly nicer to fetch them from there, since we already store them in there in main.bicep

**Comment by kjaymiller** [comment]
This is already setup for appservice, did we do the same for ACA?

**Comment by pamelafox** [comment]
Looks like not yet: https://github.com/kjaymiller/cookiecutter-relecloud/blob/main/%7B%7Bcookiecutter.__src_folder_name%7D%7D/infra/web.bicep#L70
