### ISSUE TITLE
🐛 Django Postgres ACA test fails when trying to access database

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/cookiecutter-relecloud#72]
To Reproduce:

1. Create new Django project via cookiecutter with all defaults
2. cd into built project and open in devcontainer/codespace
3. run python -m pytest

**Comment by pamelafox** [comment]
Fixed, twas due to using live server, DB was getting cleared:
https://pytest-django.readthedocs.io/en/latest/database.html#populate-the-test-database-if-you-use-transactional-or-live-server
Has to be a function-scope fixture when using live server.
