### ISSUE TITLE
removes lab from cookiecutter-relecloud

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/cookiecutter-relecloud#74]
At the moment the lab is not updating for the version of deployment. It's fine if in the future we'd like to auto deploy labs but I think for now each individual repo can be responsible for their own lab/content.

**Comment by pamelafox** [comment]
That makes sense, would you be removing it from the original Pycon repo as well, however? (Or just leaving it there and assuming the cruft process won't delete it)

**Comment by kjaymiller** [comment]
> That makes sense, would you be removing it from the original Pycon repo as well, however? (Or just leaving it there and assuming the cruft process won't delete it)

My hope is that it won't delete it. I'll be testing that before

**Comment by kjaymiller** [comment]
@pamelafox - cruft has a `skip` parameter in the `cruft.json` where you can ignore changes to files.
